### ISSUE TITLE
git-jump

### ISSUE THREAD

**Issue by Konfekt** [andlrc/git-open#2]
It would be interesting to compare it to [git-jump](https://github.com/git/git/blob/master/contrib/git-jump/git-jump) that comes with Git, in particular `git jump diff` that seems to achieve something similar to `git-open` for corresponding inputs, say `git jump diff HEAD` seems close to `git open --changed`.
One difference is that git jump passes the exact locations of the changes but seems to be mainly aimed at Vim and Emacs.

**Comment by andlrc** [comment]
TBH I dumped the code for this at GH, but havn't used it for a very long time, as I simply use `git jump ...`.

    git open --staged     =>  git jump diff --staged
    git open --changed    =>  git jump diff
    git open --committed  =>  git jump diff HEAD~ 
    git open --dry-run    ~> GIT_EDITOR=cat\ -- git jump diff ...

**Comment by andlrc** [comment]
FWIW then `git jump ...` added support for `--stdout` some time ago, meaning you could use it to open files in any editor with something like:

    ${EITOR:-vi} $(git jump --stdout diff ... | awk -F: '{ print $1 }')

**Comment by Konfekt** [comment]
Yes, thank you, I was under the same impression that git jump suffices as a Vim user.
